INSERT INTO CUSTOMER (NAME, EMAIL, CREATED_DATE) VALUES ('MAKS', '111@gmail.com', '2017-01-11');
INSERT INTO CUSTOMER (NAME, EMAIL, CREATED_DATE) VALUES ('Alex', '113@gmail.com', '2017-02-11');
INSERT INTO CUSTOMER (NAME, EMAIL, CREATED_DATE) VALUES ('Banana', '114@gmail.com', '2017-03-11');

INSERT INTO MUSIC (SONG_NAME, AUTHOR, CREATED_DATE) VALUES ('5 Years Time', 'Noah And The Whale', '2017-01-11');
INSERT INTO MUSIC (SONG_NAME, AUTHOR, CREATED_DATE) VALUES ('Different Colors', 'TALKING IS HARD', '2017-02-11');
INSERT INTO MUSIC (SONG_NAME, AUTHOR, CREATED_DATE) VALUES ('In The Morning', 'Razorlight', '2017-03-11');
INSERT INTO MUSIC (SONG_NAME, AUTHOR, CREATED_DATE) VALUES ('Goldrushed', 'Royal', '2017-03-11');
INSERT INTO MUSIC (SONG_NAME, AUTHOR, CREATED_DATE) VALUES ('Kids', 'MGMT', '2017-03-11');
INSERT INTO MUSIC (SONG_NAME, AUTHOR, CREATED_DATE) VALUES ('Sweet Disposition', ' The Temper Trap', '2017-03-11');

INSERT INTO MOVIES (MOVIE_NAME, PRODUCER, CREATION_YEAR) VALUES ('The Green Mile', 'Frank Darabont', '1999');
INSERT INTO MOVIES (MOVIE_NAME, PRODUCER, CREATION_YEAR) VALUES ('Batman', 'Leslie H. Martinson', '1966');
INSERT INTO MOVIES (MOVIE_NAME, PRODUCER, CREATION_YEAR) VALUES ('The Truman Show', 'Peter Weir', '1998');

INSERT INTO MOVIES_MUSIC (MOVIE_ID, SONG_ID) VALUES (1, 1);
INSERT INTO MOVIES_MUSIC (MOVIE_ID, SONG_ID) VALUES (1, 2);
INSERT INTO MOVIES_MUSIC (MOVIE_ID, SONG_ID) VALUES (1, 3);
INSERT INTO MOVIES_MUSIC (MOVIE_ID, SONG_ID) VALUES (2, 1);

INSERT INTO ORDERS (QUANTITY, ORDER_DATE, SONG_ID) VALUES (1, '2017-01-11 : 15:25:04', 1);
INSERT INTO ORDERS (QUANTITY, ORDER_DATE, SONG_ID) VALUES (11, '2016-12-30 : 20:00:55', 2);
INSERT INTO ORDERS (QUANTITY, ORDER_DATE, SONG_ID) VALUES (5, '2015-05-21 : 11:26:41', 2);