DROP TABLE IF EXISTS customers.CUSTOMER;
DROP TABLE IF EXISTS customers.ORDERS;
DROP TABLE IF EXISTS customers.MUSIC;
DROP TABLE IF EXISTS customers.MOVIES_MUSIC;
DROP TABLE IF EXISTS customers.MOVIES;

CREATE TABLE customers.CUSTOMER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100),
  CREATED_DATE DATE NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE customers.MUSIC (
  ID INT NOT NULL AUTO_INCREMENT,
  SONG_NAME VARCHAR(100) NOT NULL,
  AUTHOR VARCHAR(100),
  CREATED_DATE DATE NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE customers.MOVIES (
  ID INT NOT NULL AUTO_INCREMENT,
  MOVIE_NAME VARCHAR(100) NOT NULL,
  PRODUCER VARCHAR(100),
  CREATION_YEAR INT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE customers.MOVIES_MUSIC (
  ID INT NOT NULL AUTO_INCREMENT,
  MOVIE_ID INT NOT NULL,
  SONG_ID INT NOT NULL ,
  PRIMARY KEY (ID),
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID),
  FOREIGN KEY (SONG_ID) REFERENCES MUSIC(ID)
);

CREATE TABLE customers.ORDERS (
  ID INT NOT NULL AUTO_INCREMENT,
  QUANTITY INTEGER,
  ORDER_DATE DATETIME NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE ORDERS ADD COLUMN SONG_ID INT NOT NULL;
ALTER TABLE ORDERS ADD CONSTRAINT FOREIGN KEY (SONG_ID) REFERENCES MUSIC(ID);
