DROP TABLE IF EXISTS customers.CUSTOMER;
DROP TABLE IF EXISTS customers.ORDERS;

CREATE TABLE customers.CUSTOMER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100),
  CREATED_DATE DATE NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE customers.ORDERS (
  ID INT NOT NULL AUTO_INCREMENT,
  ITEM VARCHAR(100) NOT NULL,
  QUANTITY INTEGER,
  ORDER_DATE DATETIME NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE ORDERS ADD COLUMN CUSTOMER_ID INT NOT NULL;
ALTER TABLE ORDERS ADD CONSTRAINT FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);
